databases:
  - name: db_production
    ipAllowList: []
    databaseName: 
    user: truphy

services:
  - type: web
    name: my_bus
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false