# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# production:
#   <<: *default
#   url: <%= ENV['DATABASE_URL'] %>
#   database: bussapp_production
#   username: bussapp_render
#   password: '@Truphy1.'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: 'truphy'
  password: '@Truphy1.'
  database: 'db_production'

development:
  <<: *default
  database: 'mydev'

test:
  <<: *default
  database: 'mytest'

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  

