MPESA_CONSUMER_KEY: 'lfPeIPhZ7KDHfyNCFILttArLsKhZv0Ma'
MPESA_CONSUMER_SECRET: 'Voqvlbj5qApy6YEK'
MPESA_PASSKEY: 'fef66eba0f3f6485df404ac4980e3f49924cc8a8b3e6ef7dd6bbc238cdd0629c'
MPESA_SHORTCODE: '6437127'
CALLBACK_URL: 'https://lets-ride-fe42d9bf40d4.herokuapp.com/api/stkquery'